@url=https://cinema.kolei.ru
#@url=http://localhost:3019

# https://swagger.kolei.ru?url=https://cinema.kolei.ru/swagger/cinema.yml

### регистрация
POST {{url}}/auth/register
Content-Type: application/json

{
    "email":"nothere@inthe.net",
    "password":"qwerty",
    "firstName":"qq",
    "lastName":"ww"
}

### Авторизация
POST {{url}}/auth/login
Content-Type: application/json

{
    "email":"nothere@inthe.net",
    "password":"qwerty"
}


### Получение списка фильмов
GET {{url}}/movies?filter=new
Authorization: Bearer 430857s

### Получение картинки
GET {{url}}/up/images/duna.webp