@url=http://localhost:3000/api

### получение списка блюд
GET {{url}}/menu-item

### Добавление блюда в корзину
POST {{url}}/cart
Content-Type: application/json

{
    "menuItemId": 1,
    "quantity": 1
}

### Изменение количества блюда в корзине
PATCH {{url}}/cart/1
Content-Type: application/json

{
    "quantity": 10
}

### Удаление блюда из корзины
DELETE {{url}}/cart/1

### Авторизация
POST {{url}}/user/login
Content-Type: application/json

{
    "login": "login",
    "password": "123456"
}

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJpYXQiOjE3NDc3MjQ4MDJ9.qX7eLwPNxXm_LE-TgA2P9Z-G-RBF5WmYD3IwJZaK4Nc
### Получение корзины пользователя
GET {{url}}/cart
Authorization: Bearer {{token}}